import 'package:flutter/material.dart';

import '../waypoints/waypoint_category.dart';

/// How a track is drawn: the repeated direction arrow, and the colours it needs.

/// The MapLibre image name for the direction arrow repeated along a track.
const trackArrowImage = 'owm-track-arrow';

/// Where that image is bundled. Generated by
/// `tools/icons/build_waypoint_icons.py` alongside the category glyphs.
const trackArrowAsset = 'assets/waypoint_icons/track-arrow.png';

/// Arrows sit on top of the line, so they cannot be the line's colour.
///
/// Drawing them in the track colour makes them vanish into it — the whole point
/// of the arrow is lost on exactly the tracks whose colour the user chose most
/// deliberately. White reads on everything except a white or yellow track, so
/// the choice is made per track from its own luminance rather than fixed.
String arrowColourFor(Color track) =>
    ThemeData.estimateBrightnessForColor(track) == Brightness.dark
    ? '#FFFFFF'
    : '#212121';

/// Arrow width in logical pixels.
///
/// Twice the line width, which reads as an arrowhead set into the line rather
/// than a separate mark stuck on top of it. At 13 it burst visibly out of both
/// sides of the track on a device.
const trackArrowSizeDp = 10.0;

/// Screen distance between arrows, in pixels.
///
/// MapLibre's default of 250 put one arrow on a two-kilometre track and none at
/// all on a short one, and a track with no arrow reads as having no direction
/// rather than as being short. Symbols are laid out at whole zoom levels and then
/// scaled, so the spacing actually seen varies either side of this.
const trackArrowSpacing = 50.0;

/// Line width in logical pixels for a saved track.
const trackLineWidth = 5.0;

/// The colour a track's line is drawn in, honouring a per-track override.
String trackLineColour(WaypointColour? colour, WaypointCategory category) =>
    hexColour(colour?.value ?? category.colour);
